---
Name: omnipay-moneris
After:
  - 'framework/*'
  - 'cms/*'
---

# Extensions
Payment:
  allowed_gateways:
    - 'Moneris'
  has_one:
    Order: Order
  summary_fields: 
    ID: 'Payment ID'
    Order.OrderNumber: 'Order Number'
    Money: 'Amount'
    GatewayTitle: 'Gateway'
    PaymentStatus: 'Status'
    LastMessage.Message: 'Last Message'
    Created.Nice: 'Created'
        
  searchable_fields:
    - Money
    - Status
    - Created
  extensions:
    - PaymentExtension

SilverStripe\Omnipay\PaymentGatewayController:
  extensions:
    - PaymentGatewayControllerExtension

GatewayMessage:
  store_gateway_data: true
  extensions: 
    - GatewayMessageExtension
    
GatewayRequestMessage:
  extensions: 
    - GatewayRequestMessageExtension

GatewayResponseMessage:
  extensions: 
    - GatewayResponseMessageExtension
    
GatewayErrorMessage:
  extensions: 
    - GatewayErrorMessageExtension