---
Name: omnipay-moneris
After:
  - 'framework/*'
  - 'cms/*'
---

# Extensions
Payment:
  allowed_gateways:
    - 'Moneris'
  has_one:
    Order: Order
  extensions:
    - PaymentExtension

SilverStripe\Omnipay\PaymentGatewayController:
  extensions:
    - PaymentGatewayControllerExtension

GatewayRequestMessage:
  store_parameters: true
  extensions: 
    - GatewayRequestMessageExtension

GatewayResponseMessage:
  store_data: true
  extensions: 
    - GatewayResponseMessageExtension