---
Name: omnipay-moneris
After:
  - 'framework/*'
  - 'cms/*'
---

# Extensions
Payment:
  allowed_gateways:
    - 'Moneris'
  has_one:
    Order: Order
  extensions:
    - PaymentExtension

SilverStripe\Omnipay\PaymentGatewayController:
  extensions:
    - PaymentGatewayControllerExtension

GatewayMessage:
  store_gateway_data: true
  extensions: 
    - GatewayMessageExtension
    
GatewayRequestMessage:
  extensions: 
    - GatewayRequestMessageExtension

GatewayResponseMessage:
  extensions: 
    - GatewayResponseMessageExtension
    
GatewayErrorMessage:
  extensions: 
    - GatewayErrorMessageExtension